### PR TITLE
fix: utilize new API for yvBOOST and UNI [WEB-407]

### PR DESCRIPTION
**Pull request by x48-crypto**

### CODE REVIEW

**Comment by yearn-integrations** [comment]
## Important changes detected  (payment related code)
- Found address [0x9d409a0A012CFbA9B15F6D4B36Ac57A46966Ab9a](https://etherscan.io/address/0x9d409a0A012CFbA9B15F6D4B36Ac57A46966Ab9a) in files app/containers/Vaults/saga.js. This address is from vault `yvBOOST`  
- Found address [0xFBEB78a723b8087fD2ea7Ef1afEc93d35E8Bed42](https://etherscan.io/address/0xFBEB78a723b8087fD2ea7Ef1afEc93d35E8Bed42) in files app/containers/Vaults/saga.js. This address is from vault `yvUNI`

**Comment by dudesahn** [comment]
yveCRV TVL isn't showing up now, even though it is working fine in the API. 

Screen Shot 2021-06-23 at 10 40 02 PM

**Comment by dudesahn** [comment]
My issue above seems to only be if you use the vercel preview, but pr-373.yearn.dev/vaults works fine
Screen Shot 2021-06-23 at 10 45 03 PM

However, this TVL doesn't match what's in the API, so idk wtf is going on lol

**Comment by yearn-integrations** [comment]
## Important changes detected  (payment related code)
- Found address [0x9d409a0A012CFbA9B15F6D4B36Ac57A46966Ab9a](https://etherscan.io/address/0x9d409a0A012CFbA9B15F6D4B36Ac57A46966Ab9a) in files app/containers/Vaults/saga.js. This address is from vault `yvBOOST`  
- Found address [0xFBEB78a723b8087fD2ea7Ef1afEc93d35E8Bed42](https://etherscan.io/address/0xFBEB78a723b8087fD2ea7Ef1afEc93d35E8Bed42) in files app/containers/Vaults/saga.js. This address is from vault `yvUNI`

**Pull request merged**
