### PR TITLE
fix: handle unsupported EIP-1559 network error [WEB-704]

### PR DESCRIPTION
**Pull request by xgambitox**
- Add support for legacy transactions when metamask v10 + hw wallets errors out trying to use EIP-1559 type 2 transactions.

### CODE REVIEW

**Comment by yearn-integrations** [comment]
## Important changes detected  (payment related code)
- Found constant `GASPRICES_API` in files app/containers/Zapper/saga.js (`+  const GASPRICES_API = 'https://api.blocknative.com/gasprices/blockprices';`), app/containers/Zapper/saga.js (`+    const response = await request(GASPRICES_API, { headers: HEADERS });`)  
- Found constant `BLOCKNATIVE_DAPP_ID` in files app/containers/Zapper/saga.js (`+    Authorization: process.env.BLOCKNATIVE_DAPP_ID,`)  
- Found constant `DEFAULT_CONFIDENCE_LEVEL` in files app/containers/Zapper/saga.js (`+  const DEFAULT_CONFIDENCE_LEVEL = 95;`), app/containers/Zapper/saga.js (`+      ({ confidence }) => confidence === DEFAULT_CONFIDENCE_LEVEL,`)  
- Found constant `TX_BROADCASTED` in files app/drizzle/store/DrizzleContract.js (`-            type: 'TX_BROADCASTED',`), app/drizzle/store/DrizzleContract.js (`+              type: 'TX_BROADCASTED',`)  
- Found constant `TX_CONFIRMAITON` in files app/drizzle/store/DrizzleContract.js (`-            type: 'TX_CONFIRMAITON',`), app/drizzle/store/DrizzleContract.js (`+              type: 'TX_CONFIRMAITON',`)  
- Found constant `TX_SUCCESSFUL` in files app/drizzle/store/DrizzleContract.js (`+              type: 'TX_SUCCESSFUL',`), app/drizzle/store/DrizzleContract.js (`-            type: 'TX_SUCCESSFUL',`)  
- Found constant `TX_ERROR` in files app/drizzle/store/DrizzleContract.js (`+              type: 'TX_ERROR',`), app/drizzle/store/DrizzleContract.js (`-            type: 'TX_ERROR',`)  
- Found keyword `web3` in files app/containers/Zapper/saga.js (`-          web3.eth.sendTransaction,`), app/containers/Zapper/saga.js (`+        yield call(sendTx, web3, approvalTransaction, broadcastTransaction);`), app/containers/Zapper/saga.js (`-      web3.eth.sendTransaction,`), app/containers/Zapper/saga.js (`+    yield call(sendTx, web3, zapInTransaction, broadcastTransaction);`), app/containers/Zapper/saga.js (`-        web3.eth.sendTransaction,`), app/containers/Zapper/saga.js (`+      yield call(sendTx, web3, approvalTransaction, broadcastTransaction);`), app/containers/Zapper/saga.js (`+    yield call(sendTx, web3, zapOutTransaction, broadcastTransaction);`), app/containers/Zapper/saga.js (`+const sendTx = async (web3, transactionObject, callback) => {`), app/containers/Zapper/saga.js (`+    txObj.maxPriorityFeePerGas = web3.utils.toWei(`), app/containers/Zapper/saga.js (`+    txObj.maxFeePerGas = web3.utils.toWei(`), app/containers/Zapper/saga.js (`+  return web3.eth.sendTransaction(txObj, callback).catch((error) => {`), app/containers/Zapper/saga.js (`+      txObj.gasPrice = web3.utils.toWei(`), app/containers/Zapper/saga.js (`+      return web3.eth.sendTransaction(txObj, callback);`), app/drizzle/store/DrizzleContract.js (`+          sendArgs.gasPrice = web3.utils.toWei(`)

**Review by turtlemoji — APPROVED** [review]

**Comment by turtlemoji** [comment]
Check and account for estimated price if request fail and then we can merge

**Comment by yearn-integrations** [comment]
## Important changes detected  (payment related code)
- Found constant `GASPRICES_API` in files app/containers/Zapper/saga.js (`+  const GASPRICES_API = 'https://api.blocknative.com/gasprices/blockprices';`), app/containers/Zapper/saga.js (`+    const response = await request(GASPRICES_API, { headers: HEADERS });`)  
- Found constant `BLOCKNATIVE_DAPP_ID` in files app/containers/Zapper/saga.js (`+    Authorization: process.env.BLOCKNATIVE_DAPP_ID,`)  
- Found constant `DEFAULT_CONFIDENCE_LEVEL` in files app/containers/Zapper/saga.js (`+  const DEFAULT_CONFIDENCE_LEVEL = 95;`), app/containers/Zapper/saga.js (`+      ({ confidence }) => confidence === DEFAULT_CONFIDENCE_LEVEL,`)  
- Found constant `TX_BROADCASTED` in files app/drizzle/store/DrizzleContract.js (`-            type: 'TX_BROADCASTED',`), app/drizzle/store/DrizzleContract.js (`+              type: 'TX_BROADCASTED',`)  
- Found constant `TX_CONFIRMAITON` in files app/drizzle/store/DrizzleContract.js (`-            type: 'TX_CONFIRMAITON',`), app/drizzle/store/DrizzleContract.js (`+              type: 'TX_CONFIRMAITON',`)  
- Found constant `TX_SUCCESSFUL` in files app/drizzle/store/DrizzleContract.js (`+              type: 'TX_SUCCESSFUL',`), app/drizzle/store/DrizzleContract.js (`-            type: 'TX_SUCCESSFUL',`)  
- Found constant `TX_ERROR` in files app/drizzle/store/DrizzleContract.js (`+              type: 'TX_ERROR',`), app/drizzle/store/DrizzleContract.js (`-            type: 'TX_ERROR',`)  
- Found keyword `web3` in files app/containers/Zapper/saga.js (`-          web3.eth.sendTransaction,`), app/containers/Zapper/saga.js (`+        yield call(sendTx, web3, approvalTransaction, broadcastTransaction);`), app/containers/Zapper/saga.js (`-      web3.eth.sendTransaction,`), app/containers/Zapper/saga.js (`+    yield call(sendTx, web3, zapInTransaction, broadcastTransaction);`), app/containers/Zapper/saga.js (`-        web3.eth.sendTransaction,`), app/containers/Zapper/saga.js (`+      yield call(sendTx, web3, approvalTransaction, broadcastTransaction);`), app/containers/Zapper/saga.js (`+    yield call(sendTx, web3, zapOutTransaction, broadcastTransaction);`), app/containers/Zapper/saga.js (`+const sendTx = async (web3, transactionObject, callback) => {`), app/containers/Zapper/saga.js (`+  const gasPrice = await web3.eth.getGasPrice();`), app/containers/Zapper/saga.js (`+    txObj.maxPriorityFeePerGas = web3.utils.toWei(`), app/containers/Zapper/saga.js (`+    txObj.maxFeePerGas = web3.utils.toWei(`), app/containers/Zapper/saga.js (`+  return web3.eth.sendTransaction(txObj, callback).catch((error) => {`), app/containers/Zapper/saga.js (`+        ? web3.utils.toWei(estimatedPrice.price.toString(), 'gwei')`), app/containers/Zapper/saga.js (`+      return web3.eth.sendTransaction(txObj, callback);`), app/drizzle/store/DrizzleContract.js (`+      const gasPrice = await web3.eth.getGasPrice();`), app/drizzle/store/DrizzleContract.js (`+            ? web3.utils.toWei(estimatedPrice.price.toString(), 'gwei')`)

**Review by turtlemoji — APPROVED** [review]

**Comment by dudesahn** [comment]
@xgambitox tested with MM9 and 10, with and without ledger. 

All four work; and on MM10 + ledger we get this error in the console, which I think is expected

Screen Shot 2021-08-16 at 9 44 39 PM

**Review by dudesahn — APPROVED** [review]

**Pull request merged**
