### PR TITLE
feat: update yveCRV copy to suggest buying on Sushi [WEB-469]

### PR DESCRIPTION
**Pull request by patcito**

### CODE REVIEW

**Comment by yearn-integrations** [comment]
## Important changes detected  (payment related code)
- Found address [0xd533a949740bb3306d119cc777fa900ba034cd52](https://etherscan.io/address/0xd533a949740bb3306d119cc777fa900ba034cd52) in files app/components/Vault/index.js. This address is from token `CRV`  
- Found address [0xc5bddf9843308380375a611c18b50fb9341f502a](https://etherscan.io/address/0xc5bddf9843308380375a611c18b50fb9341f502a) in files app/components/Vault/index.js. This address is from vault `yveCRV`

**Comment by dudesahn** [comment]
Looks good, just need to add a space between "market" and "than"

Screen Shot 2021-06-29 at 10 25 23 AM

**Comment by yearn-integrations** [comment]
## Important changes detected  (payment related code)
- Found address [0xd533a949740bb3306d119cc777fa900ba034cd52](https://etherscan.io/address/0xd533a949740bb3306d119cc777fa900ba034cd52) in files app/components/Vault/index.js. This address is from token `CRV`  
- Found address [0xc5bddf9843308380375a611c18b50fb9341f502a](https://etherscan.io/address/0xc5bddf9843308380375a611c18b50fb9341f502a) in files app/components/Vault/index.js. This address is from vault `yveCRV`

**Comment by patcito** [comment]
Pushed a fix.

**Review by xgambitox — APPROVED** [review]

**Comment by yearn-integrations** [comment]
## Important changes detected  (payment related code)
- Found address [0xd533a949740bb3306d119cc777fa900ba034cd52](https://etherscan.io/address/0xd533a949740bb3306d119cc777fa900ba034cd52) in files app/components/Vault/index.js. This address is from token `CRV`  
- Found address [0xc5bddf9843308380375a611c18b50fb9341f502a](https://etherscan.io/address/0xc5bddf9843308380375a611c18b50fb9341f502a) in files app/components/Vault/index.js. This address is from vault `yveCRV`

**Pull request merged**
