### PR TITLE
feat: new lazy ape button [WEB-221]

### PR DESCRIPTION
**Pull request by turtlemoji**
Reimplements the lazy ape button with the new v2 vaults

### CODE REVIEW

**Review by x48-crypto — APPROVED** [review]
Looks good from a code standpoint. @dudesahn are you able to find someone to QA this?

**Comment by dudesahn** [comment]
@turtlemoji please update the copy to show vault symbol as opposed to underlying symbol. So for GUSD, it should read:

"Head to PowerPool and deposit yvCurve-GUSD for additional yield in the Yearn Lazy Ape pool.
This pool allows you to earn swap fees on top of your yVault yield."

Vault symbols are: yvCurve-GUSD, yvCurve-Compound, yvCurve-yBUSD, yvCurve-GUSD, yUSD

**Review by x48-crypto — APPROVED** [review]

**Comment by turtlemoji** [comment]
Modified to use `vault.symbol` instead of `vault.tokenAlias` @dudesahn

**Comment by dudesahn** [comment]
Looks good, merging

**Review by dudesahn — APPROVED** [review]

**Pull request merged**
