### PR TITLE
feat: migrate crvUSDN and crvUSDP to v2

### PR DESCRIPTION
**Pull request by patcito**

### CODE REVIEW

**Comment by patcito** [comment]
- Found address [0x881b06da56BB5675c54E4Ed311c21E54C5025298](https://etherscan.io/address/0x881b06da56BB5675c54E4Ed311c21E54C5025298) in files app/containers/Vaults/customOrder.json. This address is from vault `yLINK`  
- Found address [0x1B5eb1173D2Bf770e50F10410C9a96F7a8eB6e75](https://etherscan.io/address/0x1B5eb1173D2Bf770e50F10410C9a96F7a8eB6e75) in files app/containers/Vaults/customOrder.json, app/containers/Vaults/migrationWhitelist.json. This address is from vault `yvusdp3CRV`  
- Found address [0xFe39Ce91437C76178665D64d7a2694B0f6f17fE3](https://etherscan.io/address/0xFe39Ce91437C76178665D64d7a2694B0f6f17fE3) in files app/containers/Vaults/customOrder.json, app/containers/Vaults/migrationWhitelist.json. This address is from vault `yvusdn3CRV`  
- Found address [0x7047F90229a057C13BF847C0744D646CFb6c9E1A](https://etherscan.io/address/0x7047F90229a057C13BF847C0744D646CFb6c9E1A) in files app/containers/Vaults/customOrder.json. This address is from vault `yvCurve-renBTC`  
- Found address [0xC4dAf3b5e2A9e93861c3FBDd25f1e943B8D87417](https://etherscan.io/address/0xC4dAf3b5e2A9e93861c3FBDd25f1e943B8D87417) in files app/containers/Vaults/customOrder.json, app/containers/Vaults/migrationWhitelist.json. This address is from vault `yvCurve-USDP`  
- Found address [0x3B96d491f067912D18563d56858Ba7d6EC67a6fa](https://etherscan.io/address/0x3B96d491f067912D18563d56858Ba7d6EC67a6fa) in files app/containers/Vaults/customOrder.json, app/containers/Vaults/migrationWhitelist.json. This address is from vault `yvCurve-USDN`  
- Found address [0x7Eb40E450b9655f4B3cC4259BCC731c63ff55ae6](https://etherscan.io/address/0x7Eb40E450b9655f4B3cC4259BCC731c63ff55ae6) in files app/containers/Vaults/migrationWhitelist.json. This address is from token `usdp3CRV`  
- Found address [0x4f3E8F405CF5aFC05D68142F3783bDfE13811522](https://etherscan.io/address/0x4f3E8F405CF5aFC05D68142F3783bDfE13811522) in files app/containers/Vaults/migrationWhitelist.json. This address is from token `usdn3CRV`

**Review by x48-crypto — APPROVED** [review]

**Review by fameal — APPROVED** [review]
Looks good

**Review by nymmrx — APPROVED** [review]
lgtm

**Comment by dudesahn** [comment]
I updated the custom order to remove duplicates from v1, and complete revamped ordering of the stablecoin vaults in v2

**Pull request merged**
