### PR TITLE
feat(wallets): add support for gnosis safe

### PR DESCRIPTION
**Pull request by mikheevm**
- Add gnosis safe to list of supported wallets
- bump ngrok to the version that is compatible with ARM
- add manifest.json file and copy it to the build folder to supply app info to the gnosis app, add support for cors on the server
- *need help on this one*: remove `net.isListening()` check before dispatching that wallet is connected
Gnosis Safe doesn't support listening, but since the result value is not checked anywhere (it can return `true` or `false`) it seems to be obsolete, therefore I removed it to make it work

### CODE REVIEW

**Review by xgambitox — APPROVED** [review]

**Comment by mikheevm** [comment]
I can't figure out how to support cors for manifest.json, I added https://github.com/yearn/yearn-finance/pull/400/commits/a3580ce1b1bd71d5fe734484409cc1f16856d2c2 but it didn't do the job. Could you please help me with that? Otherwise, I will take another look tomorrow.

**Comment by xgambitox** [comment]
> I can't figure out how to support cors for manifest.json, I added [a3580ce](https://github.com/yearn/yearn-finance/commit/a3580ce1b1bd71d5fe734484409cc1f16856d2c2) but it didn't do the job. Could you please help me with that? Otherwise, I will take another look tomorrow.

Hey @mikheevm! Maybe you can try using the `webpack-pwa-manifest` plugin [here](https://github.com/yearn/yearn-finance/blob/develop/internals/webpack/webpack.prod.babel.js#L129) and try including the `crossorigin` property as referenced in [docs](https://github.com/arthurbergmz/webpack-pwa-manifest), hopefully it works and no need to use the `copy-webpack-plugin`

**Comment by mikheevm** [comment]
this option is for HTML `crossorigin` attribute: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin

**Comment by mikheevm** [comment]
@xgambitox managed to resolve it, the problem was express static middleware overwriting my route handler

**Comment by mikheevm** [comment]
Screenshot 2021-07-28 at 14 54 38

It will look like this :)

**Review by xgambitox — APPROVED** [review]

**Review by x48-crypto — APPROVED** [review]

**Pull request merged**
